// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4678.Cybercavs2016Code.subsystems;

import org.usfirst.frc4678.Cybercavs2016Code.Robot;
import org.usfirst.frc4678.Cybercavs2016Code.RobotMap;
import org.usfirst.frc4678.Cybercavs2016Code.commands.SetPickupArm;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class PickupArm extends Subsystem {
	public int pickupState = 0;
	public int spitState = 0;
	PowerDistributionPanel pdp = new PowerDistributionPanel();
	int count = 0;
	int cnt = 0;
	int cnt1 = 0;
	int wristStartPosition = 0;
	int elbowStartPosition = 0;
	double elbowPosition = 0;
	double elbowSpeed = 0;
	double wristPosition = 0;
	double wristSpeed = 0;
	double wristPositionError = 0;
	double elbowPositionError = 0;
	double kWrist = 0;
	double kElbow = 0;
	double[][] positionSpeed = new double[][]{
		{23959, 656.0, 41016, -3.0},
		{24648, 609.0, 41016, -16.0},
		{24648, 565.0, 40822, -48.0},
		{24648, 532.0, 40822, -108.0},
		{24648, 505.0, 40822, -195.0},
		{24648, 473.0, 40822, -301.0},
		{24648, 421.0, 40822, -413.0},
		{24991, 343.0, 40822, -522.0},
		{24991, 250.0, 39943, -621.0},
		{24991, 159.0, 39943, -708.0},
		{24991, 85.0, 39943, -782.0},
		{24991, 27.0, 39943, -848.0},
		{24991, -14.0, 39943, -905.0},
		{24903, -58.0, 39943, -951.0},
		{24903, -111.0, 38746, -983.0},
		{24903, -180.0, 38746, -1000.0},
		{24903, -180.0, 38746, -997.0},
		{24903, -258.0, 38746, -978.0},
		{24903, -339.0, 38746, -978.0},
		{24325, -415.0, 38746, -947.0},
		{24325, -482.0, 37714, -914.0},
		{24325, -536.0, 37714, -882.0},
		{24325, -584.0, 37714, -853.0},
		{24325, -627.0, 37714, -822.0},
		{24325, -670.0, 37714, -789.0},
		{23426, -714.0, 37714, -752.0},
		{23426, -761.0, 36919, -716.0},
		{23426, -808.0, 36919, -679.0},
		{23426, -856.0, 36919, -645.0},
		{23426, -904.0, 36919, -612.0},
		{23426, -954.0, 36919, -578.0},
		{22195, -1004.0, 36919, -539.0},
		{22195, -1056.0, 36404, -493.0},
		{22195, -1108.0, 36404, -439.0},
		{22195, -1160.0, 36404, -381.0},
		{22195, -1211.0, 36404, -324.0},
		{22195, -1258.0, 36404, -278.0},
		{20627, -1258.0, 36404, -242.0},
		{20627, -1300.0, 36175, -215.0},
		{20627, -1334.0, 36175, -215.0},
		{20627, -1357.0, 36175, -190.0},
		{20627, -1367.0, 36175, -163.0},
		{20627, -1362.0, 36175, -131.0},
		{19054, -1340.0, 36175, -97.0},
		{19054, -1302.0, 36143, -64.0},
		{19054, -1247.0, 36143, -37.0},
		{19054, -1172.0, 36143, -17.0},
		{19054, -1074.0, 36143, -5.0},
		{19054, -950.0, 36143, 0.0},
		{18183, -810.0, 36143, 0.0},
		{18183, -663.0, 36143, 0.0},
		{18183, -513.0, 36143, 2.0},
		{18183, -368.0, 36143, 11.0},
		{18183, -231.0, 36143, 39.0},
		{18183, -115.0, 36143, 113.0},
		{18163, -26.0, 36143, 250.0},
		{18163, 25.0, 36929, 440.0},
		{18163, 50.0, 36929, 653.0},
		{18163, 50.0, 36929, 851.0},
		{18163, 64.0, 36929, 999.0},
		{18163, 87.0, 36929, 999.0},
		{18372, 125.0, 36929, 1087.0},
		{18372, 177.0, 38384, 1134.0},
		{18372, 236.0, 38384, 1174.0},
		{18372, 297.0, 38384, 1220.0},
		{18372, 362.0, 38384, 1269.0},
		{18372, 434.0, 38384, 1304.0},
		{19057, 512.0, 38384, 1317.0},
		{19057, 589.0, 39885, 1301.0},
		{19057, 657.0, 39885, 1267.0},
		{19057, 709.0, 39885, 1224.0},
		{19057, 747.0, 39885, 1178.0},
		{19057, 774.0, 39885, 1128.0},
		{20033, 800.0, 39885, 1070.0},
		{20033, 831.0, 40952, 997.0},
		{20033, 872.0, 40952, 905.0},
		{20033, 926.0, 40952, 793.0},
		{20033, 984.0, 40952, 663.0},
		{20033, 1037.0, 40952, 525.0},
		{21322, 1037.0, 40952, 385.0},
		{21322, 1074.0, 41151, 258.0},
		{21322, 1090.0, 41151, 154.0},
		{21322, 1084.0, 41151, 154.0},
		{21322, 1061.0, 41151, 80.0},
		{21322, 1031.0, 41151, 33.0},
		{22485, 999.0, 41151, 9.0}
	};
	String armMode;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon pickupElbowMotor = RobotMap.pickupArmpickupElbowMotor;
    private final CANTalon pickupWristMotor = RobotMap.pickupArmpickupWristMotor;
    private final CANTalon pickupWheels = RobotMap.pickupArmpickupWheels;
    private final DigitalInput ballSensor = RobotMap.pickupArmballSensor;
    private final DigitalInput backBallSensor = RobotMap.pickupArmbackBallSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
	int wristHoldPosition = Robot.holdWristPosition();
	int wristPickupPosition = Robot.wristPullInPosition();
	int wristSpitOutPosition = Robot.spitOutWristPosition();
	int elbowHoldPosition = Robot.holdElbowPosition();
	int elbowPickupPosition = Robot.pickupElbowPosition();
	int elbowSpitOutPosition = Robot.spitOutElbowPosition();

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new SetPickupArm());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	//////////////////////////////////////
	////////// Access functions//////////
	/////////////////////////////////////

	public int getElbowPosition() {	return pickupElbowMotor.getEncPosition();}

	public int getWristPosition() {return pickupWristMotor.getEncPosition();}

	public int getPickupWheelsPosition() {	return pickupWheels.getEncPosition();}

	public double getCurrent(int channel) {	return pdp.getCurrent(channel);}
	
	public double getWristError() {return pickupWristMotor.getError();}
	
	public String getArmMode() {return armMode;}

	public int getWristAngular() {return pickupWristMotor.getPulseWidthPosition();}
	
	public int getElbowAngular() {return pickupElbowMotor.getPulseWidthPosition();}
	
	public boolean getBackSensor() {return backBallSensor.get();}
	
	/////////////////////////////////////
	////////// Setter functions//////////
	/////////////////////////////////////
	
	public void setPickupWheelsMode(int mode) {
		if (mode == 0) {
			pickupWheels.changeControlMode(TalonControlMode.Current);
		}
		if (mode == 1) {
			pickupWheels.changeControlMode(TalonControlMode.Disabled);
		}
		if (mode == 2) {
			pickupWheels.changeControlMode(TalonControlMode.Follower);
		}
		if (mode == 3) {
			pickupWheels.changeControlMode(TalonControlMode.MotionProfile);
		}
		if (mode == 4) {
			pickupWheels.changeControlMode(TalonControlMode.PercentVbus);
		}
		if (mode == 5) {
			pickupWheels.changeControlMode(TalonControlMode.Position);
		}
		if (mode == 6) {
			pickupWheels.changeControlMode(TalonControlMode.Speed);
		}
		if (mode == 7) {
			pickupWheels.changeControlMode(TalonControlMode.Voltage);
		}
	}

	public void setElbowMode(int mode) {
		if (mode == 0) {
			pickupElbowMotor.changeControlMode(TalonControlMode.Current);
		}
		if (mode == 1) {
			pickupElbowMotor.changeControlMode(TalonControlMode.Disabled);
		}
		if (mode == 2) {
			pickupElbowMotor.changeControlMode(TalonControlMode.Follower);
		}
		if (mode == 3) {
			pickupElbowMotor.changeControlMode(TalonControlMode.MotionProfile);
		}
		if (mode == 4) {
			pickupElbowMotor.changeControlMode(TalonControlMode.PercentVbus);
		}
		if (mode == 5) {
			pickupElbowMotor.changeControlMode(TalonControlMode.Position);
		}
		if (mode == 6) {
			pickupElbowMotor.changeControlMode(TalonControlMode.Speed);
		}
		if (mode == 7) {
			pickupElbowMotor.changeControlMode(TalonControlMode.Voltage);
		}
	}

	public void setWristMode(int mode) {
		if (mode == 0) {
			pickupWristMotor.changeControlMode(TalonControlMode.Current);
		}
		if (mode == 1) {
			pickupWristMotor.changeControlMode(TalonControlMode.Disabled);
		}
		if (mode == 2) {
			pickupWristMotor.changeControlMode(TalonControlMode.Follower);
		}
		if (mode == 3) {
			pickupWristMotor.changeControlMode(TalonControlMode.MotionProfile);
		}
		if (mode == 4) {
			pickupWristMotor.changeControlMode(TalonControlMode.PercentVbus);
		}
		if (mode == 5) {
			pickupWristMotor.changeControlMode(TalonControlMode.Position);
		}
		if (mode == 6) {
			pickupWristMotor.changeControlMode(TalonControlMode.Speed);
		}
		if (mode == 7) {
			pickupWristMotor.changeControlMode(TalonControlMode.Voltage);
		}
	}

	public void setPickupWheels(double voltage) {
		pickupWheels.set(voltage);
	}
	public void resetPickupState() {
		pickupState = 0;
	}
	public void resetSpitState() {
		spitState = 0;
	}
	public void resetArmEncValues() {
		pickupElbowMotor.setEncPosition(0);
		pickupWristMotor.setEncPosition(0);
	}
	public void setArmMode(String Mode) {
		armMode = Mode;
	}
	
	////////////////////////////////////////////////////
	////////// Functions to set Arms positions//////////
	////////////////////////////////////////////////////
	
	public void setElbowPosition(int position) {
		pickupElbowMotor.configPeakOutputVoltage(+8f, -8f); //max and min power
		pickupElbowMotor.setPID(0.2, 0, 0); //PID values
		pickupElbowMotor.setAllowableClosedLoopErr(409);
		pickupElbowMotor.set(position); // allowable error in the PID position movement
	}

	public void setWristPosition(int position) {
		pickupWristMotor.configPeakOutputVoltage(+8f, -8f); //max and min power
		pickupWristMotor.setPID(0.15, 0, 0); // PID values
		pickupWristMotor.setAllowableClosedLoopErr(409); // allowable error in the PID position movement
		pickupWristMotor.set(position);
	}
	
	
	//////////////////////////////////////////////
	//////////Arm Positioning functions//////////
	////////////////////////////////////////////
	public void pickup() {
		switch(pickupState) {
		case 0: //moves Arm to higher position and waits for wrist to be in position
			setWristPosition(wristPickupPosition);
			if (pickupElbowMotor.getEncPosition() > 10000) {  
				setWristPosition(wristPickupPosition);
				if (pickupWristMotor.getEncPosition() > 5229) { //detects if wrist is in position so that the elbow may continue moving
					setElbowPosition(elbowPickupPosition);
					setPickupWheels(Robot.pickupWheelsPower());
				}
			}
			else {
				setElbowPosition(elbowPickupPosition - 25000);//moves arm to specific location until the wrist is in position so we don't go over 15 in
			}
			if (!backBallSensor.get()) { //starts incrementing count once the back sensor sees the ball
				count++;			
			}
			else {
				count = 0;
			}
			if (count > 15) { // after 15 counts (~1/4 of a second) it assumes the ball is centered and proceeds to pick up the ball
				pickupState++;
				count = 0;
			}
		break;
		case 1://moves the wrist out and the elbow down to lift the ball over the bumper
			//System.out.println("IN CASE 1!!!!");
			setWristPosition(wristPickupPosition + 1000); 
			setElbowPosition(elbowPickupPosition + 2000);
			if (!ballSensor.get()) {
				pickupState++;
			}
		break;
		case 2: //Once elbow is high enough it will wait for the ball the settle in the catapult
			//System.out.println("IN CASE 2!!!!!");	
			setElbowPosition(elbowHoldPosition + 5000); //moves arm to this position to allow the ball to have time to settle in the robot
			count++;
			if (count > 50) {
				setPickupWheels(0);
				setArmMode("Hold");
				count = 0;
			}
		break;
		}
	}
	public void holdPosition() {
		setWristPosition(wristHoldPosition);
		if (pickupWristMotor.getPosition() > -22000) { //moves wrist first just in case the wrist is below the elbow
			setElbowPosition(elbowHoldPosition);
		}
		setPickupWheels(0);
	}
	public void spitOut() {
		switch(spitState) {
		case 0:	//reverses wheels, moves elbow
			setPickupWheels(-Robot.pickupWheelsPower());
			setElbowPosition(elbowSpitOutPosition);
			if (Math.abs(pickupElbowMotor.getError()) < 700) { //this is in the make sure the arm moves before the wrist so the wrist doesn't crash against the robot
				spitState++;
			}
		break;
		case 1: // once elbow is moved begin the move wrist
			setWristPosition(wristSpitOutPosition);
			if (pickupWristMotor.getEncPosition() < -34500) { // if wrist is in desired position is will continue
				spitState++;
			}
		break;
		case 2: //move elbow up to give the ball more push out the robot
			setElbowPosition(elbowSpitOutPosition + 8500); 
		}
	}
	
	///////////////////////////////////
	//////////Misc Functions//////////
	/////////////////////////////////
	
	public void stopArmMotors() {
		pickupElbowMotor.disable();
		pickupWristMotor.disable();
		pickupWheels.disable();
	}
	public void stopIntakeWheels() {
		pickupWheels.disable();
	}
	public void CalibratePickup() {
		wristStartPosition = (pickupWristMotor.getPulseWidthPosition() % 4096);
		elbowStartPosition = (pickupElbowMotor.getPulseWidthPosition() % 4096);
		if (wristStartPosition < 0) {
			wristStartPosition = wristStartPosition + 4096;
		}
		if (elbowStartPosition < 0) {
			elbowStartPosition = elbowStartPosition + 4096;
		}
		if (wristStartPosition < 1500) {
			wristStartPosition = wristStartPosition + 4096;
		}
		pickupWristMotor.setPulseWidthPosition(wristStartPosition);
		pickupElbowMotor.setPulseWidthPosition(elbowStartPosition);
		pickupWristMotor.setEncPosition(wristStartPosition);
		pickupElbowMotor.setEncPosition(elbowStartPosition);
	}
	public void pickupSpeedPosition() {
		//System.out.println(pickupWristMotor.getEncPosition() + ", " + pickupWristMotor.getSpeed() + ", " + pickupElbowMotor.getEncPosition() + ", " + pickupElbowMotor.getSpeed());
	}
	public void pickupOsc() {
		kElbow = 0.6;
		kWrist = 0.6;
		wristPosition = (positionSpeed[cnt][0]);
		wristSpeed = (positionSpeed[cnt][1]);
		elbowPosition = (positionSpeed[cnt][2]);
		elbowSpeed = (positionSpeed[cnt][3]);
		cnt++;
		if (cnt >= 85) {
			cnt = 0;
		}
		wristPositionError = wristPosition - pickupWristMotor.getEncPosition(); 
		elbowPositionError = elbowPosition - pickupElbowMotor.getEncPosition();
		//System.out.println(wristPosition + ", " + wristSpeed + ", " + elbowPosition + ", " + elbowSpeed + ", ");
		pickupElbowMotor.configPeakOutputVoltage(+5f, -5f); //max and min power
		pickupElbowMotor.setPID(0.2, 0, 0); //PID values
		pickupElbowMotor.setAllowableClosedLoopErr(100);
		pickupElbowMotor.set(elbowSpeed + (kElbow * elbowPositionError)); // allowable error in the PID position movement
		
		pickupWristMotor.configPeakOutputVoltage(+5f, -5f); //max and min power
		pickupWristMotor.setPID(0.15, 0, 0); // PID values
		pickupWristMotor.setAllowableClosedLoopErr(100); // allowable error in the PID position movement
		pickupWristMotor.set(wristSpeed + (kWrist * wristPositionError));
	
		
		System.out.println(wristPositionError + ", " + wristPosition + ", " + wristSpeed + ", " + elbowPositionError + ", " + elbowPosition +", " + elbowSpeed);
	}
}
